# Generated by Django 6.0.4 on 2026-05-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewiev',
            new_name='Review',
        ),
    ]
