# Generated by Django 6.0.4 on 2026-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_rename_rewiev_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Фото'),
        ),
    ]
