# Generated by Django 6.0.4 on 2026-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='full_name',
            field=models.CharField(max_length=70, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='review',
            name='position',
            field=models.CharField(max_length=80, verbose_name='Должность'),
        ),
    ]
