# Generated by Django 6.0.4 on 2026-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_alter_review_full_name_alter_review_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=350, verbose_name='Текст (отзыв)'),
        ),
    ]
