# Generated by Django 6.0.3 on 2026-05-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название сайта')),
                ('logotype', models.CharField(max_length=30, verbose_name='Логотип')),
                ('addres', models.CharField(max_length=30, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=30, verbose_name='Почта')),
                ('working_hours', models.CharField(max_length=5, verbose_name='Время работы')),
                ('instagram', models.CharField(max_length=20, verbose_name='Инстаграм')),
                ('facebook', models.CharField(max_length=20, verbose_name='Фейсбук')),
                ('wk', models.CharField(max_length=20, verbose_name='Вк')),
                ('twitter', models.CharField(max_length=20, verbose_name='Твиттер')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Ватсап')),
                ('telegram', models.CharField(max_length=20, verbose_name='Телеграмм')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
