# Generated by Django 6.0.3 on 2026-05-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграмм'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Твиттер'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ватсап'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='wk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Вк'),
        ),
    ]
