# Generated by Django 6.0.3 on 2026-05-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_sitesettings_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logotype',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Обьявление'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(max_length=30, verbose_name='Время работы'),
        ),
    ]
