# Generated by Django 6.0.4 on 2026-05-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
