# Generated by Django 6.0.4 on 2026-05-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_comments_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
