# Generated by Django 6.0.4 on 2026-05-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_comments_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
    ]
