# Generated by Django 6.0.4 on 2026-05-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternative_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Альтернативная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(blank=True, null=True, verbose_name='Скидка'),
        ),
    ]
