# Generated by Django 6.0.4 on 2026-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_alternative_price_product_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скидка'),
        ),
    ]
