# Generated by Django 6.0.4 on 2026-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
