# Generated by Django 6.0.4 on 2026-05-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
