# Generated by Django 6.0.4 on 2026-05-17 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comments_blog'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'blog')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
    ]
